### ISSUE TITLE
Add @carlosazaustre as organizer

### ISSUE THREAD

**Issue by alexfernandez** [nodeschool/madrid#11]
Hi, can anyone add @carlosazaustre to @nodeschool/chapter-organizers for Madrid?

We don't have a [team](https://github.com/orgs/nodeschool/teams) for Madrid, maybe that is the way to go?

Thanks in advance!

**Comment by Sequoia** [comment]
Hi! What's the goal? Is there an action you're trying to perform that you lack privileges for?

I'm actually not sure what the purpose of the @nodeschool/chapter-organizers team is, as it appears to grant admin access to *all* nodeschool chapter repos, which should not be necessary.

In any event, I've gone ahead and added Carlos as if that's the system we have, that's the system we have! 😸 

k les vaya bien!

**Comment by carlosazaustre** [comment]
Thanks @Sequoia !

I will take the organizer role for NodeSchool Madrid. Ready to Async!
