### ISSUE TITLE
Registro de Mentorxs: NodeSchool Madrid Reloaded Edition

### ISSUE THREAD

**Issue by carlosazaustre** [nodeschool/madrid#12]
Hola!
Estamos planeando hacer resurgir NodeSchool Madrid. El primer evento fue hace casi 3 años y fue un éxito. Unos meses más tarde repetimos con el NodeSchool International Day y desde entonces no volvimos a hacer nada.
Aún está por decidir fecha y lugar, pero si estás interesada/o en ser mentora deja tu interés en este Issue :)

-----

Mentors should be familiar with the [core NodeSchool workshoppers](http://nodeschool.io/#workshopper-list) before the event. We also encourage mentors to review the [NodeSchool Mentor Best Practices](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices) wiki page.
👋

-----
#### Mentorxs
- [x] @carlosazaustre
- [x] @fcanela 
- [x] @fsanzv 
- [x] @rubnvp 
- [x] @gootyfer 
- [x] @aljesusg 
- [x] @cbastos 
- [x] @jabadia  
- [x] @wolmi 
- [x] @carlosgoro 
- [x] @UlisesGascon 
- [x] @manufosela

#### Organizadorxs y voluntarixs
- [x] @carlosazaustre
- [ ] *¿Tu?*
- [ ] *¿Tu?*

**Comment by fcanela** [comment]
¡Me apunto! (como mentor o para ayudar como haga falta)

**Comment by fsanzv** [comment]
¡ Presente !

**Comment by rubnvp** [comment]
yo me animo también como mentor! 😃 extendamos la palabra del motor V8 al resto del mundo 🙌

**Comment by gootyfer** [comment]
Yo también me animo, claro que sí! 💪

**Comment by aljesusg** [comment]
+1

**Comment by cbastos** [comment]
+1 ;)

**Comment by jabadia** [comment]
+1

**Comment by DevJoyOps** [comment]
Buenas.

Yo también me apunto, pero como novato.
Estuve en la primera, pero al final no llegué a usarlo en ningún proyecto y
cayó en el olvido :-(
Casualmente la semana pasada me dio por refrescarlo empezando un curso, así
que la reactivación me viene de perlas.


Gracias a todos los mentores!

2018-02-25 23:02 GMT+01:00 Francisco Canela <notifications@github.com>:

**Comment by wolmi** [comment]
+1 😀

**Comment by UlisesGascon** [comment]
+1! Gran idea!!

**Comment by fcanela** [comment]
Creo que este hilo es únicamente para anotar los mentores y que @carlosazaustre tiene pensado gestionar a los asistentes más adelante. No se si los que estáis escribiendo +1 lo estáis haciendo con la intención de apuntarnos como mentores, asistentes o simplemente dar apoyo :)

**Comment by aljesusg** [comment]
Yo por mi parte mentor o si hay suficientes ayudar

**Comment by manufosela** [comment]
+1 a lo que haga falta!

**Comment by trigoporres** [comment]
+1 en voluntario

**Comment by luisddm** [comment]
+1
Estuve hace tres años en el primer evento como asistente, así que me haría mucha ilusión volver como mentor o lo que se necesite :)

**Comment by soyguijarro** [comment]
Por aquí otro que se apuntaría para ayudar :smile:
