### ISSUE TITLE
Mentor Registration: NodeSchool Madrid, 6 de Junio en La Nave (OpenExpo | OCSummit)

### ISSUE THREAD

**Issue by carlosazaustre** [nodeschool/madrid#13]
Hola mentorxs! Nuestro primer evento de la temporada será coincidiendo con el OCSummit organizado por OpenSource Weekends y OpenExpor Europa en **La Nave** el próximo **6 de Junio de 10am a 12pm**. Apúntate en éste Issue para unirte como mentor@ para el evento.

---
Los mentores deberían conocer los [Workshops Core de Nodeschool](http://nodeschool.io/#workshopper-list) antes del evento. También recomendamos a los mentores revisar la wiki de [Buenas Prácticas de NodeSchool](https://github.com/nodeschool/organizers/wiki/Event-Mentor-Best-Practices).

👋

---
#### Mentor@s
- [x] @carlosazaustre
- [x] @jabadia 
- [ ] **Tu?**
- [ ] **Tu?**

**Comment by fsanzv** [comment]
Hola @carlosazaustre, sólo a nivel informativo, el evento de Node School ¿tendrá alguna relación o vinculación con el OCSubmit o la OpenExpo Europe? ¿Podrías facilitarnos algún enlace a información de estos eventos?.

**Comment by carlosazaustre** [comment]
Hola @fsanzv !
La relación con OpenExpo y el OCSummit es básicamente que OSW (Open Source Weekends) tendrá disponible el espacio de OpenExpo durante el 6 y 7 de Junio y realizará el OCSummit (Open Communities Summit). Serán varios tracks y uno de ellos seremos NodeSchool :)

**Comment by fsanzv** [comment]
Hola de nuevo @carlosazaustre !

¿Hay algún enlace al evento OCSummit? ¿El evento es gratuito?.

Ten en cuenta que el evento se va a desarrollar en un día laborable y va a ser un esfuerzo adicional para los mentores y asistentes, cuanta más información tengamos mejor.

**Comment by carlosazaustre** [comment]
Pues por ahora no hay nada más que el programa de OpenExpo, supongo que en los próximos días la gente de OSW publicará cosas :).
Te mantengo informado por aquí

**Comment by jabadia** [comment]
Carlos, yo me apunto, no puedo editar la lista inicial, pero cuenta conmigo

**Comment by carlosazaustre** [comment]
Genial @jabadia ! te apunto!

Y algunas noticias sobre OpenExpo, habrá entrada gratuita para mentores y asistentes :)

**Comment by fsanzv** [comment]
@carlosazaustre Lo siento pero esta semana me es imposible asistir al evento. 😞

**Comment by carlosazaustre** [comment]
No problem @fsanzv ! para otra que hagamos a un "horario normal" nos vemos :)
